spring:
  application:
    name: tool-db-doc-rest
---
logging:
  config: classpath:logback.xml
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 10
      initial-size: 5
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
---
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true
  type-aliases-package: com.jaswine.tool.model
  configuration:
    jdbc-type-for-null: null
    cache-enabled: false
    multiple-result-sets-enabled: true
    default-executor-type: reuse
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    default-statement-timeout: 3000
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    return-instance-for-empty-row: false
    local-cache-scope: session